services:
  - type: web
    name: pdf-forensik
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 10000
      - key: VT_API_KEY
        value: ""
      - key: DATA_DIR
        value: /var/data
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1
